version: 0.2

phases:
  install:
    commands:
      - echo installing Nginx
      - sudo yum install nginx -y
  build:
    commands: 
      - echo Build started on 'date'
      - mkdir -p /var/www/html
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo configuring Nginx

artifacts:
  files:
    - index.html
